FB:
  comments:
    duoshuo:
      short_name: marquistj13
    provider: duoshuo
author: Marquis
banner: 学而不思则罔，思而不学则殆。
baseurl: /MyBlog
collections:
  collection_ReadingNotes_Book_NeuralNetworksAndDeepLearning:
    output: true
    permalink: /ReadingNotes/Book_NeuralNetworksAndDeepLearning/:path
  collection_ReadingNotes_test:
    output: true
    permalink: /ReadingNotes/test/:path
  collection_ScholarThings_test_scholar:
    output: true
    permalink: /ScholarThings/test_scholar/:path
defaults:
- scope:
    path: ''
    type: collection_ScholarThings_test_scholar
  values:
    layout: page
- scope:
    path: ''
    type: collection_ReadingNotes_Book_NeuralNetworksAndDeepLearning
  values:
    layout: page
- scope:
    path: ''
    type: collection_ReadingNotes_test
  values:
    layout: page
description: Actually, less is more!
email: marquistj13@gmail.com
exclude:
- README.md
- Gemfile.lock
- Gemfile
- Rakefile
- _config_with_python
gems:
- jekyll-paginate
github: https://github.com/marquistj13/
github_username: marquistj13
highlighter: rouge
include:
- _pages
kramdown:
  gfm_quirks: paragraph_end
  hard_wrap: true
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
markdown: kramdown
meta_description: Marquis个人博客
motto: It's our wits that make us men.
name: Marquis
paginate: 10
permalink: /:year/:month/:title/
resume_site: ''
url: ''
