FB:
  comments:
    provider: disqus
author: Marquis
baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
banner: 学而不思则罔，思而不学则殆。
baseurl: /MyBlog
collections:
  collection_ReadingNotes_DeepLearning:
    output: true
    permalink: /ReadingNotes/DeepLearning/:path
  collection_ReadingNotes_ProgrammingSkills:
    output: true
    permalink: /ReadingNotes/ProgrammingSkills/:path
  collection_ScholarThings_EarlyCVBasicsAndRepresentation:
    output: true
    permalink: /ScholarThings/EarlyCVBasicsAndRepresentation/:path
  collection_ScholarThings_EarlyClusteringExplore:
    output: true
    permalink: /ScholarThings/EarlyClusteringExplore/:path
  collection_ScholarThings_SLAM:
    output: true
    permalink: /ScholarThings/SLAM/:path
defaults:
- scope:
    path: ''
    type: collection_ScholarThings_EarlyCVBasicsAndRepresentation
  values:
    layout: page
- scope:
    path: ''
    type: collection_ScholarThings_EarlyClusteringExplore
  values:
    layout: page
- scope:
    path: ''
    type: collection_ScholarThings_SLAM
  values:
    layout: page
- scope:
    path: ''
    type: collection_ReadingNotes_DeepLearning
  values:
    layout: page
- scope:
    path: ''
    type: collection_ReadingNotes_ProgrammingSkills
  values:
    layout: page
description: Actually, less is more!
email: marquistj13@gmail.com
exclude:
- README.md
- Gemfile.lock
- Gemfile
- Rakefile
- _config_with_python
github: https://github.com/marquistj13/
github_username: marquistj13
highlighter: rouge
include:
- _pages
kramdown:
  gfm_quirks: paragraph_end
  hard_wrap: true
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
markdown: kramdown
meta_description: Marquis个人博客
motto: It's our wits that make us men.
name: Marquis
paginate: 10
permalink: /:year/:month/:title/
plugins:
- jekyll-paginate
- jekyll-sitemap
- jemoji
resume_site: ''
title: 侯桑的博客
url: https://marquistj13.github.io/
